# NumPy

## Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

**BONUS:** Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [1]:
import numpy as np

In [10]:
#1.
#array_unidimensional = np.random.randint(10,100,(50)) la comentamos para que no vaya cambiando con la ejecución de la celda.
print(array_unidimensional)

print(array_unidimensional[5::5])


[29 47 62 24 13 25 55 45 36 82 96 14 23 17 24 43 58 62 26 71 31 76 31 39
 21 18 95 28 92 78 49 11 90 93 39 92 85 54 61 37 24 68 42 13 57 45 52 34
 21 62]
[25 96 43 31 18 49 92 24 45]


In [13]:
#2.
#array_unidimensional1 = np.random.randint(1,21,(30))
print(array_unidimensional1)
print(array_unidimensional1[1::2])


[ 3 11  8  8 17  2 20 19  4  8 20  4  9 12 15  4  5 10 20  2  8 14  2  6
 18 13  4 16 13 16]
[11  8  2 19  8  4 12  4 10  2 14  6 13 16 16]


In [45]:
#3.
array_bidimensional1 = np.round(np.random.random_sample((4,6)),2)
array_bidimensional1_suma= np.add(array_bidimensional1,4)
#podríamos haber creado otro array igual al primero y sumarlo np.add(array1,array2)
print(array_bidimensional1_suma)


[[4.43 4.4  4.99 4.82 4.57 4.4 ]
 [4.22 4.26 4.29 4.16 4.43 4.27]
 [4.32 4.57 4.87 4.71 4.78 4.18]
 [4.37 4.43 4.61 4.99 4.87 4.86]]


In [44]:
#4.
array_bidimensional2=np.round(np.random.random_sample((6,4)),2)
print(array_bidimensional2)

print("------------------")
print(array_bidimensional2[:,2:3])

[[0.95 0.83 0.08 0.92]
 [0.59 0.39 0.32 0.34]
 [0.08 0.68 0.74 0.34]
 [0.5  0.84 0.26 0.63]
 [0.94 0.34 0.15 0.91]
 [0.43 0.83 0.   0.33]]
------------------
[[0.08]
 [0.32]
 [0.74]
 [0.26]
 [0.15]
 [0.  ]]


In [52]:
#5.
array_unidimensional2 = np.random.randint(-50,51,(30))
print(array_unidimensional2)

print("-------------------------")

array_unidimensional2[array_unidimensional2<0]

[-23  -9 -42   1  10  17  42 -27  -4 -18  34  -4 -19 -38 -35 -33 -26  42
 -49  13  27 -34  31  48 -15 -22  11   8 -38  -1]
-------------------------


array([-23,  -9, -42, -27,  -4, -18,  -4, -19, -38, -35, -33, -26, -49,
       -34, -15, -22, -38,  -1])

In [56]:
#6.
array_unidimensional3 = np.round(np.random.rand((10)),2)
print(array_unidimensional3)

condicion= array_unidimensional3>0.5
np.where(condicion)


[0.67 0.93 0.74 0.93 0.79 0.37 0.07 0.91 0.9  0.63]


(array([0, 1, 2, 3, 4, 7, 8, 9]),)

In [69]:
#7.
#array_unidimensional4 = np.random.randint(1,101,(40))
print(array_unidimensional4)

condicion1=array_unidimensional4%4==0
condicion2=array_unidimensional4%3==0

np.where(condicion1 & condicion2)

[ 17 100  87  38   8  29  51  10   6  49  61  39  40   1  39  36  24   2
  56  14   8  42  58   7   6  89  35  89  82  45  29  21  14  91  99  34
  55  92  99  20]


(array([15, 16]),)

In [63]:
#8. BONUS

array_bonus= np.random.randint(0,101,(2,3,5))
print(array_bonus)


print("---------------")

condicion_bonus= array_bonus%3==0

array_bonus_1=np.where(condicion_bonus, 0 ,array_bonus)
print(array_bonus_1)


[[[ 80  33  63  26  80]
  [ 57  91  33  47  48]
  [ 91  80 100  48  75]]

 [[ 53  67   5  34  49]
  [ 83   3  57  28  84]
  [ 14  70  61  29  58]]]
---------------
[[[ 80   0   0  26  80]
  [  0  91   0  47   0]
  [ 91  80 100   0   0]]

 [[ 53  67   5  34  49]
  [ 83   0   0  28   0]
  [ 14  70  61  29  58]]]


## Ejercicios con reshape:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [ ]:
#1.
a= np.random.randint(1,101,(2,3,4))
print(a)
print("-----------")
reshaped_a = np.reshape(a,(6,4))
print(reshaped_a)


In [ ]:
#2.
b= np.random.randint(1,60,(3,4,5))
print(a)

print("-------------------------")

reshaped_b= np.reshape(b,(15,4))
print(reshaped_b)

In [ ]:
#3.
c= np.random.random_sample((4,3,2))
print(c)

print("-------------------------")

reshaped_c= np.reshape(c,(8,3))
print(reshaped_c)

## Ejercicios con transpose:

1. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

2. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [ ]:
#1.
b= np.random.randint(1,60,(3,4,5))
print(b)

print("-------------------------")

transpose_b=np.transpose(b,(2,1,0))

print(transpose_b)

In [6]:
#2.
c= np.random.random_sample((4,3,2))
print(c)

transpose_c=np.transpose(c,(1,2,0))

print(transpose_c)


[[[0.45273276 0.71218129]
  [0.60353403 0.00521657]
  [0.51956367 0.21377812]]

 [[0.34687566 0.96721685]
  [0.83540996 0.99109446]
  [0.10613748 0.52634433]]

 [[0.68549356 0.78841529]
  [0.59241815 0.9314785 ]
  [0.59170612 0.33034917]]

 [[0.28844323 0.96829695]
  [0.11750379 0.27204092]
  [0.97086995 0.21995544]]]
[[[0.45273276 0.34687566 0.68549356 0.28844323]
  [0.71218129 0.96721685 0.78841529 0.96829695]]

 [[0.60353403 0.83540996 0.59241815 0.11750379]
  [0.00521657 0.99109446 0.9314785  0.27204092]]

 [[0.51956367 0.10613748 0.59170612 0.97086995]
  [0.21377812 0.52634433 0.33034917 0.21995544]]]


## Preguntas teóricas:

1. ¿Qué diferencia existe entre el reshape y el transpose?

2. ¿Y entre el transpose y el swapaxes?

1. la diferencia e/ transpose y reshape; 
para el primero hacemos el cambio a partir de la indexación y para el segundo no
para el primero no podemos cambiar dimensión pero para el reshape sí.
*pnte añadir más info.

2. la diferencia e/ trasnpose y swapaxes;
sólo s epueden intercambiar dos ejes para el swapaexes y el el transpose todos los que queramos.

## Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

3. Si el valor del array es igual que la media, se reemplaza por "A".

4. Si el valor del array es mayor que la media, se reemplaza por "B".

5. Si el valor del array es menor que la media, se reemplaza por "C".

6. Si el valor es igual que el máximo, se reemplaza por "D".

7. Si el valor es igual que el mínimo, se reemplaza por "E".

In [49]:
# 1.
array_3=np.round(np.random.random_sample((2,3,5)),1)
print(array_3)


[[[0.1 1.  0.3 0.2 0.6]
  [0.1 0.6 0.5 0.  1. ]
  [0.2 0.7 0.5 0.6 0.9]]

 [[0.6 0.1 0.7 0.9 0.8]
  [0.7 0.8 0.8 0.3 0.6]
  [0.3 0.7 0.2 0.8 0.9]]]


In [52]:
#2.
array_vacio=np.round(np.empty((2,3,5)),1)
print(array_vacio)

print(array_3)

print("------------")

media_array=np.round(np.mean(array_3),1)

print(media_array)

print("------------")


condicion_array = media_array == array_3

array_3_1=np.where(condicion_array, "A", array_3)

print(array_3_1)



[[[0.1 1.  0.3 0.2 0.6]
  [0.1 0.6 0.5 0.  1. ]
  [0.2 0.7 0.5 0.6 0.9]]

 [[0.6 0.1 0.7 0.9 0.8]
  [0.7 0.8 0.8 0.3 0.6]
  [0.3 0.7 0.2 0.8 0.9]]]
[[[0.1 1.  0.3 0.2 0.6]
  [0.1 0.6 0.5 0.  1. ]
  [0.2 0.7 0.5 0.6 0.9]]

 [[0.6 0.1 0.7 0.9 0.8]
  [0.7 0.8 0.8 0.3 0.6]
  [0.3 0.7 0.2 0.8 0.9]]]
------------
0.6
------------
[[['0.1' '1.0' '0.3' '0.2' 'A']
  ['0.1' 'A' '0.5' '0.0' '1.0']
  ['0.2' '0.7' '0.5' 'A' '0.9']]

 [['A' '0.1' '0.7' '0.9' '0.8']
  ['0.7' '0.8' '0.8' '0.3' 'A']
  ['0.3' '0.7' '0.2' '0.8' '0.9']]]


In [53]:
condicion_array2 = media_array < array_3

array_3_1=np.where(condicion_array2, "B", array_3_1)

print(array_3_1)

[[['0.1' 'B' '0.3' '0.2' 'A']
  ['0.1' 'A' '0.5' '0.0' 'B']
  ['0.2' 'B' '0.5' 'A' 'B']]

 [['A' '0.1' 'B' 'B' 'B']
  ['B' 'B' 'B' '0.3' 'A']
  ['0.3' 'B' '0.2' 'B' 'B']]]


In [54]:
condicion_array3 = media_array > array_3

array_3_1=np.where(condicion_array3, "c", array_3_1)

print(array_3_1)

[[['c' 'B' 'c' 'c' 'A']
  ['c' 'A' 'c' 'c' 'B']
  ['c' 'B' 'c' 'A' 'B']]

 [['A' 'c' 'B' 'B' 'B']
  ['B' 'B' 'B' 'c' 'A']
  ['c' 'B' 'c' 'B' 'B']]]


In [55]:
condicion_max= np.max(array_3)==array_3
array_3_1=np.where(condicion_max, "D", array_3_1)

print(array_3_1)

[[['c' 'D' 'c' 'c' 'A']
  ['c' 'A' 'c' 'c' 'D']
  ['c' 'B' 'c' 'A' 'B']]

 [['A' 'c' 'B' 'B' 'B']
  ['B' 'B' 'B' 'c' 'A']
  ['c' 'B' 'c' 'B' 'B']]]


In [56]:
condicion_min= np.min(array_3)==array_3
array_3_1=np.where(condicion_min, "E", array_3_1)

print(array_3_1)

[[['c' 'D' 'c' 'c' 'A']
  ['c' 'A' 'c' 'E' 'D']
  ['c' 'B' 'c' 'A' 'B']]

 [['A' 'c' 'B' 'B' 'B']
  ['B' 'B' 'B' 'c' 'A']
  ['c' 'B' 'c' 'B' 'B']]]
